2022-02-02 23:16:30.931 +02:00 [INF] Worker running at: "2022-02-02T23:16:30.9249070+02:00"
2022-02-02 23:17:21.810 +02:00 [INF] Migrating and seeding db from PortalDbContextSeeder
2022-02-02 23:17:32.103 +02:00 [INF] Db seeding completed
2022-02-02 23:17:56.570 +02:00 [INF] Received User Summary: {"User":{"Id":1,"Email":"admin.cea@covport.check","Name":"cea","UserRole":"ADMIN","DateCreated":"2022-02-02T22:37:26.1312620","DateUpdated":"2022-02-02T22:37:26.1321580","$type":"User"},"Bookings":[{"Id":2,"UserId":1,"SpaceId":4,"Status":"PENDING","TestType":"PCR","LocationName":"SEYCHELLES","DateCreated":"2022-02-02T22:37:31.9960360","DateUpdated":"2022-02-02T22:37:31.9960810","$type":"Booking"}],"Tests":[],"$type":"UserSummary"}
2022-02-02 23:17:56.932 +02:00 [INF] HTTP GET /api/user/summary/1?id=1 responded 200 in 1596.1772 ms
2022-02-02 23:35:18.338 +02:00 [INF] Received Space response: [{"Id":1,"LocationName":"SEYCHELLES","Date":"2022-02-02T00:00:00.0000000","SpacesCreated":30,"Closed":false,"DateCreated":"2022-02-02T22:37:29.3383160","DateUpdated":"2022-02-02T22:37:29.3389080","$type":"Space"},{"Id":2,"LocationName":"MALTA","Date":"2022-02-02T00:00:00.0000000","SpacesCreated":20,"Closed":false,"DateCreated":"2022-02-02T22:37:29.3401630","DateUpdated":"2022-02-02T22:37:29.3401910","$type":"Space"},{"Id":3,"LocationName":"GREENLAND","Date":"2022-02-02T00:00:00.0000000","SpacesCreated":30,"Closed":false,"DateCreated":"2022-02-02T22:37:29.3402070","DateUpdated":"2022-02-02T22:37:29.3402190","$type":"Space"},{"Id":4,"LocationName":"SEYCHELLES","Date":"2022-02-03T00:00:00.0000000","SpacesCreated":30,"Closed":false,"DateCreated":"2022-02-02T22:37:29.3403330","DateUpdated":"2022-02-02T22:37:29.3403340","$type":"Space"},{"Id":5,"LocationName":"MALTA","Date":"2022-02-03T00:00:00.0000000","SpacesCreated":20,"Closed":false,"DateCreated":"2022-02-02T22:37:29.3403400","DateUpdated":"2022-02-02T22:37:29.3403440","$type":"Space"},{"Id":6,"LocationName":"GREENLAND","Date":"2022-02-03T00:00:00.0000000","SpacesCreated":30,"Closed":false,"DateCreated":"2022-02-02T22:37:29.3403510","DateUpdated":"2022-02-02T22:37:29.3403520","$type":"Space"}]
2022-02-02 23:35:18.430 +02:00 [INF] HTTP GET /api/space responded 200 in 9176.7368 ms
2022-02-02 23:35:25.178 +02:00 [INF] Received Space response: [{"Id":1,"LocationName":"SEYCHELLES","Date":"2022-02-02T00:00:00.0000000","SpacesCreated":30,"Closed":false,"DateCreated":"2022-02-02T22:37:29.3383160","DateUpdated":"2022-02-02T22:37:29.3389080","$type":"Space"},{"Id":2,"LocationName":"MALTA","Date":"2022-02-02T00:00:00.0000000","SpacesCreated":20,"Closed":false,"DateCreated":"2022-02-02T22:37:29.3401630","DateUpdated":"2022-02-02T22:37:29.3401910","$type":"Space"},{"Id":3,"LocationName":"GREENLAND","Date":"2022-02-02T00:00:00.0000000","SpacesCreated":30,"Closed":false,"DateCreated":"2022-02-02T22:37:29.3402070","DateUpdated":"2022-02-02T22:37:29.3402190","$type":"Space"},{"Id":4,"LocationName":"SEYCHELLES","Date":"2022-02-03T00:00:00.0000000","SpacesCreated":30,"Closed":false,"DateCreated":"2022-02-02T22:37:29.3403330","DateUpdated":"2022-02-02T22:37:29.3403340","$type":"Space"},{"Id":5,"LocationName":"MALTA","Date":"2022-02-03T00:00:00.0000000","SpacesCreated":20,"Closed":false,"DateCreated":"2022-02-02T22:37:29.3403400","DateUpdated":"2022-02-02T22:37:29.3403440","$type":"Space"},{"Id":6,"LocationName":"GREENLAND","Date":"2022-02-03T00:00:00.0000000","SpacesCreated":30,"Closed":false,"DateCreated":"2022-02-02T22:37:29.3403510","DateUpdated":"2022-02-02T22:37:29.3403520","$type":"Space"}]
2022-02-02 23:35:25.212 +02:00 [INF] HTTP GET /api/space responded 200 in 481.8500 ms
2022-02-02 23:35:32.197 +02:00 [ERR] Received request errors: User Unauthorized when calling {Request.Path}
2022-02-02 23:35:32.216 +02:00 [INF] HTTP POST /api/space responded 401 in 786.9964 ms
2022-02-02 23:35:35.848 +02:00 [ERR] Received request errors: Space Closed when calling {Request.Path}
2022-02-02 23:35:35.862 +02:00 [INF] HTTP POST /api/space responded 400 in 582.3151 ms
2022-02-02 23:35:49.946 +02:00 [ERR] Failed executing DbCommand (530ms) [Parameters=[@p0='?' (DbType = Boolean), @p1='?' (DbType = DateTime2), @p2='?' (DbType = DateTime2), @p3='?' (DbType = DateTime2), @p4='?' (Size = 450), @p5='?' (DbType = Int32)], CommandType='"Text"', CommandTimeout='30']
SET NOCOUNT ON;
INSERT INTO [Spaces] ([Closed], [Date], [DateCreated], [DateUpdated], [LocationName], [SpacesCreated])
VALUES (@p0, @p1, @p2, @p3, @p4, @p5);
SELECT [Id]
FROM [Spaces]
WHERE @@ROWCOUNT = 1 AND [Id] = scope_identity();
2022-02-02 23:35:50.383 +02:00 [ERR] An exception occurred in the database while saving changes for context type 'Infrastructure.Persistence.PortalDbContext'.
Microsoft.EntityFrameworkCore.DbUpdateException: An error occurred while updating the entries. See the inner exception for details.
 ---> Microsoft.Data.SqlClient.SqlException (0x80131904): Cannot insert duplicate key row in object 'dbo.Spaces' with unique index 'IX_Spaces_LocationName_Date'. The duplicate key value is (Greenland, 2022-02-02 00:00:00.0000000).
The statement has been terminated.
   at Microsoft.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__169_0(Task`1 result)
   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location ---
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.ExecuteAsync(IRelationalConnection connection, CancellationToken cancellationToken)
ClientConnectionId:92631abb-81f0-413f-95e0-ddfb4c9c2fcf
Error Number:2601,State:1,Class:14
   --- End of inner exception stack trace ---
   at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.ExecuteAsync(IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.ExecuteAsync(IEnumerable`1 commandBatches, IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.ExecuteAsync(IEnumerable`1 commandBatches, IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.ExecuteAsync(IEnumerable`1 commandBatches, IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChangesAsync(IList`1 entriesToSave, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChangesAsync(DbContext _, Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerExecutionStrategy.ExecuteAsync[TState,TResult](TState state, Func`4 operation, Func`4 verifySucceeded, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.DbContext.SaveChangesAsync(Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)
Microsoft.EntityFrameworkCore.DbUpdateException: An error occurred while updating the entries. See the inner exception for details.
 ---> Microsoft.Data.SqlClient.SqlException (0x80131904): Cannot insert duplicate key row in object 'dbo.Spaces' with unique index 'IX_Spaces_LocationName_Date'. The duplicate key value is (Greenland, 2022-02-02 00:00:00.0000000).
The statement has been terminated.
   at Microsoft.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__169_0(Task`1 result)
   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location ---
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.ExecuteAsync(IRelationalConnection connection, CancellationToken cancellationToken)
ClientConnectionId:92631abb-81f0-413f-95e0-ddfb4c9c2fcf
Error Number:2601,State:1,Class:14
   --- End of inner exception stack trace ---
   at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.ExecuteAsync(IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.ExecuteAsync(IEnumerable`1 commandBatches, IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.ExecuteAsync(IEnumerable`1 commandBatches, IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.ExecuteAsync(IEnumerable`1 commandBatches, IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChangesAsync(IList`1 entriesToSave, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChangesAsync(DbContext _, Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerExecutionStrategy.ExecuteAsync[TState,TResult](TState state, Func`4 operation, Func`4 verifySucceeded, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.DbContext.SaveChangesAsync(Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)
2022-02-02 23:35:50.394 +02:00 [ERR] Received request errors: An error occurred while updating the entries. See the inner exception for details. when calling {Request.Path}
2022-02-02 23:35:50.402 +02:00 [ERR] HTTP POST /api/space responded 500 in 2165.4684 ms
2022-02-02 23:35:59.211 +02:00 [ERR] Failed executing DbCommand (376ms) [Parameters=[@p0='?' (DbType = Boolean), @p1='?' (DbType = DateTime2), @p2='?' (DbType = DateTime2), @p3='?' (DbType = DateTime2), @p4='?' (Size = 450), @p5='?' (DbType = Int32)], CommandType='"Text"', CommandTimeout='30']
SET NOCOUNT ON;
INSERT INTO [Spaces] ([Closed], [Date], [DateCreated], [DateUpdated], [LocationName], [SpacesCreated])
VALUES (@p0, @p1, @p2, @p3, @p4, @p5);
SELECT [Id]
FROM [Spaces]
WHERE @@ROWCOUNT = 1 AND [Id] = scope_identity();
2022-02-02 23:35:59.560 +02:00 [ERR] An exception occurred in the database while saving changes for context type 'Infrastructure.Persistence.PortalDbContext'.
Microsoft.EntityFrameworkCore.DbUpdateException: An error occurred while updating the entries. See the inner exception for details.
 ---> Microsoft.Data.SqlClient.SqlException (0x80131904): Cannot insert duplicate key row in object 'dbo.Spaces' with unique index 'IX_Spaces_LocationName_Date'. The duplicate key value is (Greenland, 2022-02-03 00:00:00.0000000).
The statement has been terminated.
   at Microsoft.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__169_0(Task`1 result)
   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location ---
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.ExecuteAsync(IRelationalConnection connection, CancellationToken cancellationToken)
ClientConnectionId:92631abb-81f0-413f-95e0-ddfb4c9c2fcf
Error Number:2601,State:1,Class:14
   --- End of inner exception stack trace ---
   at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.ExecuteAsync(IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.ExecuteAsync(IEnumerable`1 commandBatches, IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.ExecuteAsync(IEnumerable`1 commandBatches, IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.ExecuteAsync(IEnumerable`1 commandBatches, IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChangesAsync(IList`1 entriesToSave, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChangesAsync(DbContext _, Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerExecutionStrategy.ExecuteAsync[TState,TResult](TState state, Func`4 operation, Func`4 verifySucceeded, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.DbContext.SaveChangesAsync(Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)
Microsoft.EntityFrameworkCore.DbUpdateException: An error occurred while updating the entries. See the inner exception for details.
 ---> Microsoft.Data.SqlClient.SqlException (0x80131904): Cannot insert duplicate key row in object 'dbo.Spaces' with unique index 'IX_Spaces_LocationName_Date'. The duplicate key value is (Greenland, 2022-02-03 00:00:00.0000000).
The statement has been terminated.
   at Microsoft.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__169_0(Task`1 result)
   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location ---
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.ExecuteAsync(IRelationalConnection connection, CancellationToken cancellationToken)
ClientConnectionId:92631abb-81f0-413f-95e0-ddfb4c9c2fcf
Error Number:2601,State:1,Class:14
   --- End of inner exception stack trace ---
   at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.ExecuteAsync(IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.ExecuteAsync(IEnumerable`1 commandBatches, IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.ExecuteAsync(IEnumerable`1 commandBatches, IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.ExecuteAsync(IEnumerable`1 commandBatches, IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChangesAsync(IList`1 entriesToSave, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChangesAsync(DbContext _, Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerExecutionStrategy.ExecuteAsync[TState,TResult](TState state, Func`4 operation, Func`4 verifySucceeded, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.DbContext.SaveChangesAsync(Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)
2022-02-02 23:35:59.572 +02:00 [ERR] Received request errors: An error occurred while updating the entries. See the inner exception for details. when calling {Request.Path}
2022-02-02 23:35:59.581 +02:00 [ERR] HTTP POST /api/space responded 500 in 1535.8892 ms
2022-02-02 23:38:02.808 +02:00 [INF] Space created and saved: {"Id":9,"LocationName":"Greenland","Date":"2022-02-04T00:00:00.0000000","SpacesCreated":20,"Closed":false,"DateCreated":"2022-02-02T23:38:01.6531960+02:00","DateUpdated":"2022-02-02T23:38:01.6531960+02:00","$type":"Space"}
2022-02-02 23:38:02.855 +02:00 [INF] HTTP POST /api/space responded 200 in 1650.1920 ms
2022-02-02 23:38:16.798 +02:00 [ERR] Failed executing DbCommand (350ms) [Parameters=[@p0='?' (DbType = Boolean), @p1='?' (DbType = DateTime2), @p2='?' (DbType = DateTime2), @p3='?' (DbType = DateTime2), @p4='?' (Size = 450), @p5='?' (DbType = Int32)], CommandType='"Text"', CommandTimeout='30']
SET NOCOUNT ON;
INSERT INTO [Spaces] ([Closed], [Date], [DateCreated], [DateUpdated], [LocationName], [SpacesCreated])
VALUES (@p0, @p1, @p2, @p3, @p4, @p5);
SELECT [Id]
FROM [Spaces]
WHERE @@ROWCOUNT = 1 AND [Id] = scope_identity();
2022-02-02 23:38:17.169 +02:00 [ERR] An exception occurred in the database while saving changes for context type 'Infrastructure.Persistence.PortalDbContext'.
Microsoft.EntityFrameworkCore.DbUpdateException: An error occurred while updating the entries. See the inner exception for details.
 ---> Microsoft.Data.SqlClient.SqlException (0x80131904): Cannot insert duplicate key row in object 'dbo.Spaces' with unique index 'IX_Spaces_LocationName_Date'. The duplicate key value is (Greenland, 2022-02-03 00:00:00.0000000).
The statement has been terminated.
   at Microsoft.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__169_0(Task`1 result)
   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location ---
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.ExecuteAsync(IRelationalConnection connection, CancellationToken cancellationToken)
ClientConnectionId:92631abb-81f0-413f-95e0-ddfb4c9c2fcf
Error Number:2601,State:1,Class:14
   --- End of inner exception stack trace ---
   at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.ExecuteAsync(IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.ExecuteAsync(IEnumerable`1 commandBatches, IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.ExecuteAsync(IEnumerable`1 commandBatches, IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.ExecuteAsync(IEnumerable`1 commandBatches, IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChangesAsync(IList`1 entriesToSave, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChangesAsync(DbContext _, Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerExecutionStrategy.ExecuteAsync[TState,TResult](TState state, Func`4 operation, Func`4 verifySucceeded, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.DbContext.SaveChangesAsync(Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)
Microsoft.EntityFrameworkCore.DbUpdateException: An error occurred while updating the entries. See the inner exception for details.
 ---> Microsoft.Data.SqlClient.SqlException (0x80131904): Cannot insert duplicate key row in object 'dbo.Spaces' with unique index 'IX_Spaces_LocationName_Date'. The duplicate key value is (Greenland, 2022-02-03 00:00:00.0000000).
The statement has been terminated.
   at Microsoft.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__169_0(Task`1 result)
   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location ---
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.ExecuteAsync(IRelationalConnection connection, CancellationToken cancellationToken)
ClientConnectionId:92631abb-81f0-413f-95e0-ddfb4c9c2fcf
Error Number:2601,State:1,Class:14
   --- End of inner exception stack trace ---
   at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.ExecuteAsync(IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.ExecuteAsync(IEnumerable`1 commandBatches, IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.ExecuteAsync(IEnumerable`1 commandBatches, IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.ExecuteAsync(IEnumerable`1 commandBatches, IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChangesAsync(IList`1 entriesToSave, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChangesAsync(DbContext _, Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerExecutionStrategy.ExecuteAsync[TState,TResult](TState state, Func`4 operation, Func`4 verifySucceeded, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.DbContext.SaveChangesAsync(Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)
2022-02-02 23:38:17.179 +02:00 [ERR] Received request errors: An error occurred while updating the entries. See the inner exception for details. when calling {Request.Path}
2022-02-02 23:38:17.192 +02:00 [ERR] HTTP POST /api/space responded 500 in 1668.6664 ms
2022-02-02 23:39:40.598 +02:00 [INF] Worker running at: "2022-02-02T23:39:40.5885790+02:00"
2022-02-02 23:39:40.708 +02:00 [INF] Migrating and seeding db from PortalDbContextSeeder
2022-02-02 23:39:47.092 +02:00 [INF] Db seeding completed
2022-02-02 23:39:47.637 +02:00 [FTL] Unable to start Kestrel.
System.Threading.Tasks.TaskCanceledException: A task was canceled.
   at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServerImpl.BindAsync(CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServerImpl.StartAsync[TContext](IHttpApplication`1 application, CancellationToken cancellationToken)
2022-02-02 23:39:57.729 +02:00 [INF] Worker running at: "2022-02-02T23:39:57.7222290+02:00"
2022-02-02 23:39:59.287 +02:00 [INF] Migrating and seeding db from PortalDbContextSeeder
2022-02-02 23:40:08.611 +02:00 [INF] Worker running at: "2022-02-02T23:40:08.6020100+02:00"
2022-02-02 23:40:09.059 +02:00 [INF] Migrating and seeding db from PortalDbContextSeeder
2022-02-02 23:40:20.114 +02:00 [INF] Worker running at: "2022-02-02T23:40:20.1071820+02:00"
2022-02-02 23:40:20.528 +02:00 [INF] Migrating and seeding db from PortalDbContextSeeder
2022-02-02 23:40:26.710 +02:00 [INF] Db seeding completed
2022-02-02 23:40:34.905 +02:00 [INF] Worker running at: "2022-02-02T23:40:34.8972770+02:00"
2022-02-02 23:40:36.649 +02:00 [INF] Migrating and seeding db from PortalDbContextSeeder
2022-02-02 23:40:43.049 +02:00 [INF] Db seeding completed
2022-02-02 23:40:59.517 +02:00 [INF] Worker running at: "2022-02-02T23:40:59.5106470+02:00"
2022-02-02 23:40:59.629 +02:00 [INF] Migrating and seeding db from PortalDbContextSeeder
2022-02-02 23:41:05.857 +02:00 [INF] Db seeding completed
2022-02-02 23:41:24.932 +02:00 [INF] Worker running at: "2022-02-02T23:41:24.9245470+02:00"
2022-02-02 23:41:25.142 +02:00 [INF] Migrating and seeding db from PortalDbContextSeeder
2022-02-02 23:41:31.777 +02:00 [INF] Db seeding completed
2022-02-02 23:42:00.828 +02:00 [ERR] Failed executing DbCommand (447ms) [Parameters=[@p0='?' (DbType = Boolean), @p1='?' (DbType = DateTime2), @p2='?' (DbType = DateTime2), @p3='?' (DbType = DateTime2), @p4='?' (Size = 450), @p5='?' (DbType = Int32)], CommandType='"Text"', CommandTimeout='30']
SET NOCOUNT ON;
INSERT INTO [Spaces] ([Closed], [Date], [DateCreated], [DateUpdated], [LocationName], [SpacesCreated])
VALUES (@p0, @p1, @p2, @p3, @p4, @p5);
SELECT [Id]
FROM [Spaces]
WHERE @@ROWCOUNT = 1 AND [Id] = scope_identity();
2022-02-02 23:42:01.363 +02:00 [ERR] An exception occurred in the database while saving changes for context type 'Infrastructure.Persistence.PortalDbContext'.
Microsoft.EntityFrameworkCore.DbUpdateException: An error occurred while updating the entries. See the inner exception for details.
 ---> Microsoft.Data.SqlClient.SqlException (0x80131904): Cannot insert duplicate key row in object 'dbo.Spaces' with unique index 'IX_Spaces_LocationName_Date'. The duplicate key value is (Greenland, 2022-02-04 00:00:00.0000000).
The statement has been terminated.
   at Microsoft.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__169_0(Task`1 result)
   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location ---
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.ExecuteAsync(IRelationalConnection connection, CancellationToken cancellationToken)
ClientConnectionId:4d602786-6ccd-4d69-8bdd-11fd4fc9188d
Error Number:2601,State:1,Class:14
   --- End of inner exception stack trace ---
   at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.ExecuteAsync(IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.ExecuteAsync(IEnumerable`1 commandBatches, IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.ExecuteAsync(IEnumerable`1 commandBatches, IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.ExecuteAsync(IEnumerable`1 commandBatches, IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChangesAsync(IList`1 entriesToSave, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChangesAsync(DbContext _, Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerExecutionStrategy.ExecuteAsync[TState,TResult](TState state, Func`4 operation, Func`4 verifySucceeded, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.DbContext.SaveChangesAsync(Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)
Microsoft.EntityFrameworkCore.DbUpdateException: An error occurred while updating the entries. See the inner exception for details.
 ---> Microsoft.Data.SqlClient.SqlException (0x80131904): Cannot insert duplicate key row in object 'dbo.Spaces' with unique index 'IX_Spaces_LocationName_Date'. The duplicate key value is (Greenland, 2022-02-04 00:00:00.0000000).
The statement has been terminated.
   at Microsoft.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__169_0(Task`1 result)
   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location ---
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.ExecuteAsync(IRelationalConnection connection, CancellationToken cancellationToken)
ClientConnectionId:4d602786-6ccd-4d69-8bdd-11fd4fc9188d
Error Number:2601,State:1,Class:14
   --- End of inner exception stack trace ---
   at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.ExecuteAsync(IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.ExecuteAsync(IEnumerable`1 commandBatches, IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.ExecuteAsync(IEnumerable`1 commandBatches, IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.ExecuteAsync(IEnumerable`1 commandBatches, IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChangesAsync(IList`1 entriesToSave, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChangesAsync(DbContext _, Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerExecutionStrategy.ExecuteAsync[TState,TResult](TState state, Func`4 operation, Func`4 verifySucceeded, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.DbContext.SaveChangesAsync(Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)
2022-02-02 23:42:01.367 +02:00 [ERR] An sql error occurred:-  An error occurred while updating the entries. See the inner exception for details.
2022-02-02 23:42:01.392 +02:00 [ERR] Received request errors: An Sql error occurred, check logs when calling {Request.Path}
2022-02-02 23:42:01.501 +02:00 [ERR] HTTP POST /api/space responded 500 in 3547.0295 ms
2022-02-02 23:42:19.357 +02:00 [INF] Received Booking response: [{"Id":1,"UserId":1,"SpaceId":1,"Status":"COMPLETED","TestType":"RAPID","LocationName":"SEYCHELLES","DateCreated":"2022-02-02T22:37:31.9945200","DateUpdated":"2022-02-02T22:37:31.9954330","$type":"Booking"},{"Id":2,"UserId":1,"SpaceId":4,"Status":"PENDING","TestType":"PCR","LocationName":"SEYCHELLES","DateCreated":"2022-02-02T22:37:31.9960360","DateUpdated":"2022-02-02T22:37:31.9960810","$type":"Booking"},{"Id":3,"UserId":2,"SpaceId":2,"Status":"COMPLETED","TestType":"PCR","LocationName":"MALTA","DateCreated":"2022-02-02T22:37:31.9960840","DateUpdated":"2022-02-02T22:37:31.9960840","$type":"Booking"},{"Id":4,"UserId":2,"SpaceId":5,"Status":"CANCELLED","TestType":"PCR","LocationName":"MALTA","DateCreated":"2022-02-02T22:37:31.9960860","DateUpdated":"2022-02-02T22:37:31.9960860","$type":"Booking"},{"Id":5,"UserId":3,"SpaceId":3,"Status":"PENDING","TestType":"PCR","LocationName":"GREENLAND","DateCreated":"2022-02-02T22:37:31.9960880","DateUpdated":"2022-02-02T22:37:31.9960880","$type":"Booking"},{"Id":6,"UserId":3,"SpaceId":1,"Status":"COMPLETED","TestType":"PCR","LocationName":"SEYCHELLES","DateCreated":"2022-02-02T22:37:31.9960900","DateUpdated":"2022-02-02T22:37:31.9960910","$type":"Booking"},{"Id":7,"UserId":3,"SpaceId":6,"Status":"PENDING","TestType":"RAPID","LocationName":"MALTA","DateCreated":"2022-02-02T22:37:31.9960920","DateUpdated":"2022-02-02T22:37:31.9960920","$type":"Booking"}]
2022-02-02 23:42:19.445 +02:00 [INF] HTTP GET /api/booking responded 200 in 940.8058 ms
2022-02-02 23:42:31.622 +02:00 [ERR] An sql error occurred:-  Space Not Found
2022-02-02 23:42:31.636 +02:00 [ERR] Received request errors: An Sql error occurred, check logs when calling {Request.Path}
2022-02-02 23:42:31.641 +02:00 [ERR] HTTP POST /api/booking responded 500 in 1412.2418 ms
2022-02-02 23:44:11.709 +02:00 [INF] Worker running at: "2022-02-02T23:44:11.7020970+02:00"
2022-02-02 23:44:11.797 +02:00 [INF] Migrating and seeding db from PortalDbContextSeeder
2022-02-02 23:44:18.190 +02:00 [INF] Db seeding completed
2022-02-02 23:44:57.225 +02:00 [INF] Worker running at: "2022-02-02T23:44:57.2162700+02:00"
2022-02-02 23:44:57.471 +02:00 [INF] Migrating and seeding db from PortalDbContextSeeder
